name: docker images build

on:
  push:
    branches:
      - 'development'
      - 'new_ci'
  workflow_dispatch:

jobs:
  build_petsc_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build Petsc Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docs/development/docker/petsc/Dockerfile
          outputs: type=docker,dest=/tmp/petsc_docker.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: petsc
          path: /tmp/petsc_docker.tar 
  
  build_lavavu_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Lavavu Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docs/development/docker/lavavu/Dockerfile
          outputs: type=docker,dest=/tmp/lavavu_docker.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lavavu
          path: /tmp/lavavu_docker.tar 
  
  build_base_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build Base Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docs/development/docker/base/Dockerfile
          outputs: type=docker,dest=/tmp/base_docker.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: base
          path: /tmp/base_docker.tar 

  build_underworld_image:
    runs-on: ubuntu-latest
    needs: build_petsc_image,build_base_image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download Petsc Image
        uses: actions/download-artifact@v2
        with:
          name: petsc
          path: /tmp
      
      - name: Download Base Image
        uses: actions/download-artifact@v2
        with:
          name: base
          path: /tmp

      - name: Load images
        run: |
          docker load --input /tmp/petsc.tar
          docker load --input /tmp/base.tar
          docker image ls -a
      
      - name: Build Underworld Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docs/development/docker/base/Dockerfile
